### ISSUE TITLE
It uses templates to build a react UI library Picker

### ISSUE THREAD

**Issue by wanglihuaya** [ddahan/ui-libs#3]
Hello, I would like to ask if I can use your project as a template to build a react ui library picker

**Comment by wanglihuaya** [comment]
Brother, your idea is really great. There are so many UI libraries now, and sometimes it’s really hard to make a choice. ❤️

**Comment by wanglihuaya** [comment]
I will note that the project and inspiration came from you, I just added the react ui libs

**Comment by ddahan** [comment]
Hi there!
Yep you can go for it, it's MIT licensed :)

But to be honest I was thinking of doing the same work for React/Svelte after Vue. Using `ui-libs.app/vue` and `ui-libs/react`. But I see now that it's a lot of work.

2nd option / suggestion: instead of building a completely separate project, we could try to use this project to avoid fragmentation? (of course you'd get full credit for you work too).

Anyway, it's your choice :) See you.

**Comment by pmaldi** [comment]
Hello @ddahan,

FYI, Apparently @wanglihuaya already does it in react but I don't think he has yet given the information. https://github.com/wanglihuaya/react-ui-libs

thank you both for the work.

**Comment by ddahan** [comment]
I see the https://github.com/wanglihuaya/react-ui-libs is unmaintained, so I guess it could still be a possibility.
I close the issue for now, but can be reopen anytime.
